# Generated by Django 4.1 on 2022-10-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeesId',
            new_name='EmployeeId',
        ),
    ]
